name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 8.0.422+5
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '8.0.422+5'

    - name: Gradle Wrapper Validation
      uses: gradle/actions/wrapper-validation@v4
      
    - name: Make gradlew executable
      run: chmod +x ./gradlew
    
    - name: Build with Gradle
      run: ./gradlew build
    
    - name: Build with Gradle (Unit tests)
      run: ./gradlew testRelease
    
    - name: Build with Gradle (lintVitalRelease)
      run: ./gradlew lintVitalRelease
  
